# Loop

In [2]:
# for loop:
for i = [1 3 5 4 10 7]
    disp(i)
end;

 1
 3
 5
 4
 10
 7


** Mean Squared Error(MSE) **: In statistics, the MSE also known as the Average Squared Error, or mean squared deviation (MSD) measures the squares of the errors or deviations. MSE is a risk function, corresponding to the expected value of the squared error loss or quadratic loss.

$${MSE}={\frac  {1}{n}}\sum _{{i=1}}^{n}({\hat  {Y_{i}}}-Y_{i})^{2} $$

In [14]:
# calculating MSE using a forloop 
E = randn(1000,1); # create a 1000 * 1 vector of random number that is normally distributed
SSE = 0; #initialization, initialize the sum of the squared error to be 0
for i = 1:1000
    SSE = SSE + E(i) * E(i); # calculate the sum of the squared error
end
MSE = SSE / 1000 #calculate the mean squared error

MSE =  0.92685


In [15]:
# In matlab, and possibly other programming lanuages, for loop is very inefficient, let's actually measure the time 
# of running this for loop
tic
SSE = 0; #initialization, initialize the sum of the squared error to be 0
for i = 1:1000
    SSE = SSE + E(i) * E(i); # calculate the sum of the squared error
end
MSE = SSE / 1000
toc

MSE =  0.92685
Elapsed time is 0.0145478 seconds.


Let's look at the MSE and see if we can use the dot product / vectorization to solve this problem

In [16]:
tic
MSE = E' * E / 1000
toc

MSE =  0.92685
Elapsed time is 0.00592613 seconds.


**This is significantly faster than using a forloop, for loop elapsed time: 0.014s, compared to the dot-product of 0.005s.**

## If-statement Demo

** In matlab, we no longer use % to find remainder, instead we use mob(a,b) **

In [25]:
X = 1:10
y = zeros(1,10)
for i = 1:10 # loop to keep track of even number
    if mod(X(i),2) == 0 # 
        y(i) = 1;
    else
        y(i) = 0;
    end
end

disp("After the loop and if" )
disp(y)

X =

    1    2    3    4    5    6    7    8    9   10

y =

   0   0   0   0   0   0   0   0   0   0

After the loop and if
   0   1   0   1   0   1   0   1   0   1


In [27]:
# Find the sum of divisible by 3 numbers in x
S = 0;
for x = X # this is common use in matlab because x just go through everything in X
    if mod(x,3) == 0
        S = S + x;
    end
end
disp(S)


 18


### while loop

In [32]:
# Again we have this row vector X and we are trying to see if 8 is in this matrix
X = 1:10
found = 0; # this means false
i = 0; # use to increment the index
while ~found  #in Matlab, we don't use the !, but instead use the ~ to denote 'not'
    i = i + 1;
    if X(i) == 8  #found it
        disp("I found it");
        found = 1;
    end
end

X =

    1    2    3    4    5    6    7    8    9   10

I found it


In [36]:
#You could also use a for loop, but it's more efficient for you to break after you found that number
for i=1:10
    fprintf('i = %d\n',i);
    if X(i)== 8
    disp("I found it")
    break
    end
end

#if you don't break, this is what will happen
disp("")
disp("Without Break statement")
for i = 1:10
    fprintf('i = %d\n',i)
    if X(i) == 8
    disp("I found it")
    end
end

i = 1
i = 2
i = 3
i = 4
i = 5
i = 6
i = 7
i = 8
I found it

Without Break statement
i = 1
i = 2
i = 3
i = 4
i = 5
i = 6
i = 7
i = 8
I found it
i = 9
i = 10


# Data Types

In [39]:
# Struct

#this is similar to the dictionar / hashmap data type
S = struct('name','bob','email','bob@example.com','contacts','123-456-789') 

S =

  scalar structure containing the fields:

    name = bob
    email = bob@example.com
    contacts = 123-456-789



In [40]:
# Cell

my_cell = {'hello world'}

my_cell = 
{
  [1,1] = hello world
}
