# Matrix in MatLab

- this document is entirely based on [Matt Dunham and Kevin Murphy's Tutorial](http://ubcmatlabguide.github.io/)

### 1. Creating a matrix succinctly

In [170]:
# Row matrices
A = 1:10 # starts at 1 increment by 1, and stop at 10
B = 1:2:10 # starts at 1, increment by 2, and stop at 10
C = 10: -1:3 # starts at 10, decrement by 1, and stops at 3

A =

    1    2    3    4    5    6    7    8    9   10

B =

    1    3    5    7    9

C =

   10    9    8    7    6    5    4    3



In [171]:
# Create an empty matrix
D = []
disp(class(D))

D = [](0x0)
double


### Several useful functions that could be used to create a matrix
Some basic function
1. zeros(rows, columns)
2. ones(rows, columns)
3. rand(rows, columns)  -> this creates a matrix of uniform random numbers in [0,1]
4. eye(dimension)  -> creates an identity matrix
5. diag(1:4)  -> this creates a 4 by 4 diagonal matrix

In [172]:
% zero matrix, one matrix,random, identity and diagonal matrix
A = zeros(4,3)
b = ones(3,4)
c = rand(2,2)
d = eye(3)
e = diag([3,4,5]) # this returns a diagonal matrix with the row vector or column vector on the diagonal
e1 = diag([3;4;5]) # column vector
e2 = diag([3,4,5],3) # place the vectors on the kth diagonal.
e3 = diag(1:4) #1:4 will create this vector [1 2 3 4]

A =

   0   0   0
   0   0   0
   0   0   0
   0   0   0

b =

   1   1   1   1
   1   1   1   1
   1   1   1   1

c =

   0.35229   0.70683
   0.60578   0.75490

d =

Diagonal Matrix

   1   0   0
   0   1   0
   0   0   1

e =

Diagonal Matrix

   3   0   0
   0   4   0
   0   0   5

e1 =

Diagonal Matrix

   3   0   0
   0   4   0
   0   0   5

e2 =

   0   0   0   3   0   0
   0   0   0   0   4   0
   0   0   0   0   0   5
   0   0   0   0   0   0
   0   0   0   0   0   0
   0   0   0   0   0   0

e3 =

Diagonal Matrix

   1   0   0   0
   0   2   0   0
   0   0   3   0
   0   0   0   4



** [meshgrid()](https://www.mathworks.com/help/matlab/ref/meshgrid.html?s_tid=doc_ta) **

In [173]:
[E,F] = meshgrid([1 2 3 4 5]) % equivalent of saying meshgrid(1:5)
[X,Y] = meshgrid(1:5,6:10) % X is a matrix where each row is a copy of x, and Y is a matrix where each column is a 
                           % of y

E =

   1   2   3   4   5
   1   2   3   4   5
   1   2   3   4   5
   1   2   3   4   5
   1   2   3   4   5

F =

   1   1   1   1   1
   2   2   2   2   2
   3   3   3   3   3
   4   4   4   4   4
   5   5   5   5   5

X =

   1   2   3   4   5
   1   2   3   4   5
   1   2   3   4   5
   1   2   3   4   5
   1   2   3   4   5

Y =

    6    6    6    6    6
    7    7    7    7    7
    8    8    8    8    8
    9    9    9    9    9
   10   10   10   10   10



** [logspace](https://www.mathworks.com/help/matlab/ref/logspace.html?s_tid=doc_ta) **: generate logarithically spaced vector
1. logspace(a,b):generate a row vector of ** 50 log spaced points **between 10^a and 10^b
2. logspace(a,b,n): genertes n points between 10^a and 10^b

In [174]:

I = logspace(0,2,6)
I1 = logspace(0,3)

I =

     1.0000     2.5119     6.3096    15.8489    39.8107   100.0000

I1 =

 Columns 1 through 6:

      1.0000      1.1514      1.3257      1.5264      1.7575      2.0236

 Columns 7 through 12:

      2.3300      2.6827      3.0888      3.5565      4.0949      4.7149

 Columns 13 through 18:

      5.4287      6.2506      7.1969      8.2864      9.5410     10.9854

 Columns 19 through 24:

     12.6486     14.5635     16.7683     19.3070     22.2300     25.5955

 Columns 25 through 30:

     29.4705     33.9322     39.0694     44.9843     51.7947     59.6362

 Columns 31 through 36:

     68.6649     79.0604     91.0298    104.8113    120.6793    138.9495

 Columns 37 through 42:

    159.9859    184.2070    212.0951    244.2053    281.1769    323.7458

 Columns 43 through 48:

    372.7594    429.1934    494.1713    568.9866    655.1286    754.3120

 Columns 49 and 50:

    868.5114   1000.0000



** [blkdiag(a,b,c,d)](https://www.mathworks.com/help/matlab/ref/blkdiag.html?s_tid=doc_ta):** creates a **block diagonal matrix** from input arguments,!!

In [175]:
%rng(1) % used to set the seed for random number, notice that Octave does not have this function implemented yet.
blockDiag = blkdiag(1,2,3,6,1)
diag([1 2 3 6 1])
blkdiag([1 2 3 6 1]) % this will NOT WORK!
a = rand(2,2)
b = ones(3,2)
blkdiag(a,b)

blockDiag =

   1   0   0   0   0
   0   2   0   0   0
   0   0   3   0   0
   0   0   0   6   0
   0   0   0   0   1

ans =

Diagonal Matrix

   1   0   0   0   0
   0   2   0   0   0
   0   0   3   0   0
   0   0   0   6   0
   0   0   0   0   1

ans =

   1   2   3   6   1

a =

   0.243429   0.325922
   0.125524   0.088855

b =

   1   1
   1   1
   1   1

ans =

   0.24343   0.32592   0.00000   0.00000
   0.12552   0.08886   0.00000   0.00000
   0.00000   0.00000   1.00000   1.00000
   0.00000   0.00000   1.00000   1.00000
   0.00000   0.00000   1.00000   1.00000



**1. [tril](https://www.mathworks.com/help/matlab/ref/tril.html) ** : construct lower triangle part of a matrix

**2. [triu](https://www.mathworks.com/help/matlab/ref/triu.html?s_tid=doc_ta) ** : construct upper triangle part of a matrix

In [176]:
a= ones(3,4)
X = tril(a)
X0 = tril(a,0) 
X1 = tril(a, 1) # the second argument k, when k > 0 : above the main diagonal,  k<0 below the main diagonal
X2a = tril(a,-1)
X2b = tril(a,-2) # the default k value is 0

Y = triu(a)
Y0 = triu(a,1)
Y1 = triu(a,-1)

a =

   1   1   1   1
   1   1   1   1
   1   1   1   1

X =

   1   0   0   0
   1   1   0   0
   1   1   1   0

X0 =

   1   0   0   0
   1   1   0   0
   1   1   1   0

X1 =

   1   1   0   0
   1   1   1   0
   1   1   1   1

X2a =

   0   0   0   0
   1   0   0   0
   1   1   0   0

X2b =

   0   0   0   0
   0   0   0   0
   1   0   0   0

Y =

   1   1   1   1
   0   1   1   1
   0   0   1   1

Y0 =

   0   1   1   1
   0   0   1   1
   0   0   0   1

Y1 =

   1   1   1   1
   1   1   1   1
   0   1   1   1



the function ** true()** and **false()** just like zeros() and ones() but create ** logical arrays ** whose 
entries take only 1 byte each rather than 32

use ** whos ** to check the variables you have currently


In [177]:
clear all
A = false(3,3)
B = zeros(3,3)
whos # whos can be used to check the variables you have currently

A =

   0   0   0
   0   0   0
   0   0   0

B =

   0   0   0
   0   0   0
   0   0   0

Variables in the current scope:

   Attr Name        Size                     Bytes  Class
   ==== ====        ====                     =====  ===== 
        A           3x3                          9  logical
        B           3x3                         72  double

Total is 18 elements using 81 bytes



   -**size(A)** to find the size of a matrix
   
   -**numel(A)**to find he number of elements in a matrix
   
   -**length(v)**usually used to find the number of elements in the column or row vector
   

In [178]:
[nrows,ncols] = size(A)
a = size(A) # this returns a 1 by 2 vector
n = numel(A)
C = 1:10
a2 = size(C)
a3 = length(C)
D = [1:11;11:21;21:31;31:41]
a4 = size(D,2)#determine the size along the specific dimension. In this case, 1 for row, and 2 for columns
a5 = size(D,1)

nrows =  3
ncols =  3
a =

   3   3

n =  9
C =

    1    2    3    4    5    6    7    8    9   10

a2 =

    1   10

a3 =  10
D =

    1    2    3    4    5    6    7    8    9   10   11
   11   12   13   14   15   16   17   18   19   20   21
   21   22   23   24   25   26   27   28   29   30   31
   31   32   33   34   35   36   37   38   39   40   41

a4 =  11
a5 =  4


**sum() ** can be used to sum up the matrix along a certain dimension

**mean()** can be used to take the averge of entries along a certain dimension

In [179]:
A = [1:4;5:8]
C = sum(A,1) # 1 for row
C2 = sum(A,2) # 2 for column
M = mean(A,1)
M2 = mean(A,2)

A =

   1   2   3   4
   5   6   7   8

C =

    6    8   10   12

C2 =

   10
   26

M =

   3   4   5   6

M2 =

   2.5000
   6.5000



The [ ] argument to the min and max functions indicate that you will specify a dimension

In [180]:
A
F1 = max(A,4) # find everything that is less than 4 and replace it with 4
F1a = min(A,5) # find everything that is larger than 5 and replace it with 5
F2 = max(A,[],2)
F3= max(A,[],1)
F4 = min(A,[],1)

A =

   1   2   3   4
   5   6   7   8

F1 =

   4   4   4   4
   5   6   7   8

F1a =

   1   2   3   4
   5   5   5   5

F2 =

   4
   8

F3 =

   5   6   7   8

F4 =

   1   2   3   4



** Matrix Concatenation **
Matrix can be concatenated by enclosing them inside of square brackets and using either a space or semicolon to specify the dimension. 

In [181]:
A = [1:5;6:10]
B = [6:10;11:15]
AB = [A B]  % this is the same as [A,B], this is a lying down matrix
AB = [A;B] % with the semicolon, it is stacking up

C = 1:5
D = [99 C 97]
D = [97 C 11:15 98]

A =

    1    2    3    4    5
    6    7    8    9   10

B =

    6    7    8    9   10
   11   12   13   14   15

AB =

    1    2    3    4    5    6    7    8    9   10
    6    7    8    9   10   11   12   13   14   15

AB =

    1    2    3    4    5
    6    7    8    9   10
    6    7    8    9   10
   11   12   13   14   15

C =

   1   2   3   4   5

D =

   99    1    2    3    4    5   97

D =

   97    1    2    3    4    5   11   12   13   14   15   98



** Matrix Basic Indexing ** Individual entries can be extracted from a matrix by simply specifying the indices inside round brackets. We can also extract several entries at once by specifying a matrix, or matrices of indices or use the : operator to extract all entries along a certain dimension

In [182]:
A
A = magic(6);
B = A(3,5) # row 3 column 5
C = A([1,2,3],4) # row 1 column 4, row 2 column 4, and row 3 column 4
D = A(4,[1,1,3])
E = A([1,2,3],[1,1,3])
F = A(:,4) # Everything on the fourth column
G = A(4,:) # Everything on the 4th row
b = magic(3)
H = b(:) # this stack everything into a row vector
I = A(end,3) # end stands for the last one, here it is the last row and 3rd column
J = A(end -1, end- 2)
K = A(5:end,4:end)
L = b(end:-1:1,:) # this will extract everything with the order of the rows reversed
M = diag(b)
N = diag(rot90(b)) # extract the counter diagonal of b
P = diag(b,-2) # this extract the diagonal entries two diagonals left and below the main
A
P2 = diag(A,-2)
P3 = diag(A,-3)
P4 = diag(A, 2)

A =

    1    2    3    4    5
    6    7    8    9   10

B =  27
C =

   26
   21
   22

D =

    8    8   33

E =

   35   35    6
    3    3    7
   31   31    2

F =

   26
   21
   22
   17
   12
   13

G =

    8   28   33   17   10   15

b =

   8   1   6
   3   5   7
   4   9   2

H =

   8
   3
   4
   1
   5
   9
   6
   7
   2

I =  29
J =  12
K =

   12   14   16
   13   18   11

L =

   4   9   2
   3   5   7
   8   1   6

M =

   8
   5
   2

N =

   6
   5
   4

P =  4
A =

   35    1    6   26   19   24
    3   32    7   21   23   25
   31    9    2   22   27   20
    8   28   33   17   10   15
   30    5   34   12   14   16
    4   36   29   13   18   11

P2 =

   31
   28
   34
   13

P3 =

    8
    5
   29

P4 =

    6
   21
   27
   15



** Logical Indexing **

In [183]:
B = A >30
B2 = A <= 10
B3 = A ~= 20

B =

   1   0   0   0   0   0
   0   1   0   0   0   0
   1   0   0   0   0   0
   0   0   1   0   0   0
   0   0   1   0   0   0
   0   1   0   0   0   0

B2 =

   0   1   1   0   0   0
   1   0   1   0   0   0
   0   1   1   0   0   0
   1   0   0   0   1   0
   0   1   0   0   0   0
   1   0   0   0   0   0

B3 =

   1   1   1   1   1   1
   1   1   1   1   1   1
   1   1   1   1   1   0
   1   1   1   1   1   1
   1   1   1   1   1   1
   1   1   1   1   1   1



In [184]:
B = A(A>30) % get all elements in A greater than 30
B1 = A(isprime(A) & (A> 20)) # get all primes in A greater than 20
#this is the same thing as using the find() function although the find() could be slower.
B2 = A(find(A>20 & isprime(A)))

B =

   35
   31
   32
   36
   33
   34

B1 =

   31
   29
   23

B2 =

   31
   29
   23



In [185]:
# To check if two matrix is equal: It is better to use the isequal() function because it will handle the case when
# the two matrix has different dimension.
test = isequal(B1,B2)
# using the == returns a matrix of logical values, not a single value.
test2 = B1 == B2
test2 = all(B1 == B2)

test =  1
test2 =

   1
   1
   1

test2 =  1


** Assignment **
   - Assignment operation, in which we change a value or values in a matrix, are perfromed in a very similar way to the indexing operations above. We indicate which entries will be changed by performing an indexing operation on the left hand side and then specify the new values on the right hand side. 
   - The right must be either a scalr value, or a matrix with the same dimension as the resulting indexed matrix on the left. Matlab automatically expands scalar values on the right to the correct size(Broadcasting)

In [186]:
A(3,2) = 999 % assigns 999 to entry (3,2)
A(:,1:3:end) = 666
A(:,1) = [2;3;5;9;7;7]
A (A == 999) = 333

# we can assign everything at once by using the colon operator
A(:) = 1:36

A =

    35     1     6    26    19    24
     3    32     7    21    23    25
    31   999     2    22    27    20
     8    28    33    17    10    15
    30     5    34    12    14    16
     4    36    29    13    18    11

A =

   666     1     6   666    19    24
   666    32     7   666    23    25
   666   999     2   666    27    20
   666    28    33   666    10    15
   666     5    34   666    14    16
   666    36    29   666    18    11

A =

     2     1     6   666    19    24
     3    32     7   666    23    25
     5   999     2   666    27    20
     9    28    33   666    10    15
     7     5    34   666    14    16
     7    36    29   666    18    11

A =

     2     1     6   666    19    24
     3    32     7   666    23    25
     5   333     2   666    27    20
     9    28    33   666    10    15
     7     5    34   666    14    16
     7    36    29   666    18    11

A =

    1    7   13   19   25   31
    2    8   14   20   26   32
    3    9   15   21 

** Deleting **
   - assigning [ ] deletes the corresponding entries from the matrix.
   - only deletions that result in a rectangular matrix are allowed

In [187]:
A
A([1,3],:) = []
A(:,end) =[]

A =

    1    7   13   19   25   31
    2    8   14   20   26   32
    3    9   15   21   27   33
    4   10   16   22   28   34
    5   11   17   23   29   35
    6   12   18   24   30   36

A =

    2    8   14   20   26   32
    4   10   16   22   28   34
    5   11   17   23   29   35
    6   12   18   24   30   36

A =

    2    8   14   20   26
    4   10   16   22   28
    5   11   17   23   29
    6   12   18   24   30



** Expansion **
- When the indices in an assignment exceed the  size of the matrix, rather than giving an error, quietly expands the matrix for you. If necessary, it pads the matrix with zeros. Using this feature is somewhat inefficient, however, as Matlab must reallocate a sufficiently large chunk of contiguous memory and copy the array.
- It is much faster to preallocate the maximum desired size with the zeros command first, whenever the maximum size is known in advance.

In [188]:
% Not very efficient codes:
[nrows, ncols] = size(A)
A(4,10) = 222

nrows =  4
ncols =  5
A =

     2     8    14    20    26     0     0     0     0     0
     4    10    16    22    28     0     0     0     0     0
     5    11    17    23    29     0     0     0     0     0
     6    12    18    24    30     0     0     0     0   222



In [195]:
B = magic(3)
C = zeros(4,6)
B(4,6) = 10

B =

   8   1   6
   3   5   7
   4   9   2

C =

   0   0   0   0   0   0
   0   0   0   0   0   0
   0   0   0   0   0   0
   0   0   0   0   0   0

B =

    8    1    6    0    0    0
    3    5    7    0    0    0
    4    9    2    0    0    0
    0    0    0    0    0   10



Linear Indexing:
- when only one dimension is specified in an indexing or assignment operation, Matlab performs linear indexing from top to buttom and then left to right.

In [199]:
A = zeros(3,5)
A(4) = 99;
A(6) = 105;
A(7) = 112

A =

   0   0   0   0   0
   0   0   0   0   0
   0   0   0   0   0

A =

     0    99   112     0     0
     0     0     0     0     0
     0   105     0     0     0



## Reshaping and Replication
- reshape a matrix from m*n to p*q, where m*n = p*q
- reshape() function
- the elements are placed in such a way so that as to preserve the order induced by linear indexing. 
- So A(11) will still equals to A(11), and so is everything else

In [206]:
A = zeros(5,6)
A(1:30) = 1:30
V = reshape(A,10,3)
check = A(11)== V(11)
check = A(14) == V(14) % any arbitrary number between 1 and 30 would yield a one

A =

   0   0   0   0   0   0
   0   0   0   0   0   0
   0   0   0   0   0   0
   0   0   0   0   0   0
   0   0   0   0   0   0

A =

    1    6   11   16   21   26
    2    7   12   17   22   27
    3    8   13   18   23   28
    4    9   14   19   24   29
    5   10   15   20   25   30

V =

    1   11   21
    2   12   22
    3   13   23
    4   14   24
    5   15   25
    6   16   26
    7   17   27
    8   18   28
    9   19   29
   10   20   30

check =  1
check =  1


In [209]:
A = [1:2;3:4]
B = repmat(A,2,3) % copy A vertically 2 times and horizontally 3 times

A =

   1   2
   3   4

B =

   1   2   1   2   1   2
   3   4   3   4   3   4
   1   2   1   2   1   2
   3   4   3   4   3   4



## Elementwise matrix arithmetic

- if one operand is a scalar value, an element-wise operation is automatically performed. 
- However, if both operands are matrices, a dot must precede the operator as in  .* .^ ./ and both matrices must be the same size

In [230]:
A = [1 2 3; 4 5 6]
B = A + 1 % since 1 is a scalar, it performs element-wise addition.
B2 = A - [0 0 2; 3 1 2] % subtraction and addition of matrices must have the same size
C = A * 3
D = A .^ 2
E = B .^ B2 %Exponentiate every entry in B by the corresponding entry in B2
H = B .* B2

% although A ./ B == B.\ A. the backslash is infrequently use, should avoid!
B ./ B2 == B2 .\ B 

A =

   1   2   3
   4   5   6

B =

   2   3   4
   5   6   7

B2 =

   1   2   1
   1   4   4

C =

    3    6    9
   12   15   18

D =

    1    4    9
   16   25   36

E =

      2      9      4
      5   1296   2401

H =

    2    6    4
    5   24   28

ans =

   1   1   1
   1   1   1



## Some Linear Algebra operations

In [239]:
A = magic(5)
B = det(A) % measure the determinant of A
C = rank(A) % the rank of A
D = trace(A) % the trace of A or the sum of diagonal entries
E = orth(A) % an orthonormal basis for range of A
F = null(A) % an orthonormal basis for the nullspace of A
[U,S,V] = svd(A) % singular value decomposition, U: orthogonal matrix, S: diagonal matrix, V is also an orthogonal matrix

A =

   17   24    1    8   15
   23    5    7   14   16
    4    6   13   20   22
   10   12   19   21    3
   11   18   25    2    9

B =  5070000
C =  5
D =  65
E =

   4.4721e-01   5.4563e-01  -5.1167e-01  -1.9544e-01   4.4976e-01
   4.4721e-01   4.4976e-01   1.9544e-01   5.1167e-01  -5.4563e-01
   4.4721e-01   2.3423e-14   6.3246e-01  -6.3246e-01   1.0783e-17
   4.4721e-01  -4.4976e-01   1.9544e-01   5.1167e-01   5.4563e-01
   4.4721e-01  -5.4563e-01  -5.1167e-01  -1.9544e-01  -4.4976e-01

F = [](5x0)
U =

  -4.4721e-01  -5.4563e-01   5.1167e-01   1.9544e-01  -4.4976e-01
  -4.4721e-01  -4.4976e-01  -1.9544e-01  -5.1167e-01   5.4563e-01
  -4.4721e-01  -2.3423e-14  -6.3246e-01   6.3246e-01  -1.0783e-17
  -4.4721e-01   4.4976e-01  -1.9544e-01  -5.1167e-01  -5.4563e-01
  -4.4721e-01   5.4563e-01   5.1167e-01   1.9544e-01   4.4976e-01

S =

Diagonal Matrix

   65.000        0        0        0        0
        0   22.547        0        0        0
        0        0   21.687        0  

## Sparse Matrices:
- when dealing with large matrices containing many zeros, you can save a great deal of space by using Matlab's ** sparse matrix construct. ** 
- Sparce Matrices can be used just like ordinary matrices but can be slower depending on the operation. 
- The function full() or sparse() convert back and forth. 

In [246]:
A = zeros(100,100);
A([1 4 8], [7 9 33]) = reshape(1:9,3,3);
n = nnz(A)  % the number of nonzero entries in A
nzeros = nonzeros(A) % all of the nonzero entries in one big column vector
A = sparse(A)
check = issparse(A) % is it really a sparse data type?
B = A * rand(100,1); % perform operations as you would with a nonsparse matrix
C = full(A);

n =  9
nzeros =

   1
   2
   3
   4
   5
   6
   7
   8
   9

A =

Compressed Column Sparse (rows = 100, cols = 100, nnz = 9 [0.09%])

  (1, 7) ->  1
  (4, 7) ->  2
  (8, 7) ->  3
  (1, 9) ->  4
  (4, 9) ->  5
  (8, 9) ->  6
  (1, 33) ->  7
  (4, 33) ->  8
  (8, 33) ->  9

check =  1
