# Lecture 2 TensorFlow Ops

- In Tensorflow, we collectively call *constants, variables, operators* as ** ops**.
- Tensorflow includes:
    1. TensorFlow
    2. TensorBoard
    3. TensorServing

## 1. TensorBoard

- a graph visualization software 
- When a user perform certain operation in a TensorBaord-activated Tensorflow program, these operations are exported to an event file.Tensorboard is able to convert these event files to graphs that can give insight into a model's behavior. 

In [13]:
import tensorflow as tf
a = tf.constant(2, name = 'a')
b = tf.constant(3, name = 'b')
x = tf.add(a,b)
with tf.Session() as sess:
    print(sess.run(x))

5


- To activate TensorBoard on this program, add the following line after you've built your computation graph, just right before running the training loop.
   
   ***writer = tf.summary.FileWriter('./graphs',sess.graph)***
   
- the first argument is to create a writer object to write operations to the event file,stored in the folder './graphs'. if you don't yet have that folder, it would automatically create it.

In [14]:
with tf.Session() as sess:
    writer = tf.summary.FileWriter('./graphs',sess.graph)
    print(sess.run(x))
          
# Remember to close the writer whenever you done using it.
writer.close()

5


- After running the above scipt, you would want to go to Terminal, make sure your present working directory is the same as your python code:

```
python nameOfTheProgram.py
tensorboard --logdir='./graphs'
```

- Then open your browser and go to http://localhost:6006/, or the link you get back after running tensorboard command
- the graph itself defines the ops and dependencies, but not displays the values. It only cares about the values when we run the session with some values to fetch in mind, for example:
    <br>***tf.Session.run(fetches, feed_dict = None, options = None, run_metadata = None)***

## 2. Constant Types

1. You can create constants of scalars or tensor values
2. syntax: *** tf.constant(value, dtype = None, shape = None, name = 'Const', verify_shape = False) ***
3. You could also create tensors whose elements are of a specific value:
    - ** tf.zeros(shape, dtype = tf.float32, name = None)**
    - **tf.zeros_like(input_tensor, dtype = None, name = None, optimize = True)**
    - **tf.ones(shape, dtype = tf.float32, name = None)**
    - **tf.ones_like(input_tensor, dtype = None, name = None, optimize = True) **
    - ** tf.fill(dims,value, name =None)**

In [17]:
# a constant of a 1d tensor, i.e. a vector
a = tf.constant([2,2], name = 'vector')

# a constant of a 2*2 tensor, i.e. a matrix
b = tf.constant([[0,1],[2,3]], name = 'b')

In [21]:
c = tf.zeros([2,3], tf.int32)
with tf.Session() as sess:
    print(sess.run(c))

[[0 0 0]
 [0 0 0]]


In [23]:
# create  a tensor of shape and type (unless type is specified) as the input_tensor but all elements are zeros
input_tensor = [[0,1],[2,3],[4,5]]
d = tf.zeros_like(input_tensor)
with tf.Session() as sess:
    print(sess.run(d))

[[0 0]
 [0 0]
 [0 0]]


In [24]:
# create a tensor of shape and all elements are ones:
tf.ones([2,3],tf.int32)

<tf.Tensor 'ones:0' shape=(2, 3) dtype=int32>

In [27]:
# tf.ones_like() is the same as tf.zeros_alike() except that this one are elements of ones:
e = tf.ones_like(input_tensor)
with tf.Session() as sess:
    print(sess.run(e))

[[1 1]
 [1 1]
 [1 1]]


In [28]:
#tf.fill() create a tensor filled with a scalar value
f = tf.fill([2,3],8)
with tf.Session() as sess:
    print(sess.run(f))

[[8 8 8]
 [8 8 8]]


You can also create constants that are sequences
- **tf.linspace(start,stop,num,name = None)**
    - this create a sequence of num evenly-spaced values that are generated beginning at start. If num > 1, the values in the sequence increase by stop - start / num -1; so that the last one is exactly stop.
    - start, stop and num MUST be a scalar
    - comparable but slightly different than numpy.linspace()
- ** tf.range(start, limit = None, delta = 1, dtype = None, name = 'range')**
    - create a sequence of numbers that begins at start and extends by increments of delta up to but not including limit. 
    
- Unlike numpy and Python sequences, Tensorflow sequences are ** NOT ITERABLE **, so if you are trying to use a for loop to iterate through them, it would NOT work!

In [40]:
g = tf.linspace(10.0,13.0,4, name = 'linespace')
with tf.Session() as sess:
    print(sess.run(g))

[ 10.  11.  12.  13.]


In [41]:
h = tf.range(3,limit = 18,delta = 3)
with tf.Session() as sess:
    print(sess.run(h))

[ 3  6  9 12 15]


In [42]:
i = tf.range(3,1,-0.5)
with tf.Session() as  sess:
    print(sess.run(i))

[ 3.   2.5  2.   1.5]


In [43]:
j = tf.range(5) # this is similar to python's builtin range, that will iterate from 0 to n-1
with tf.Session() as sess:
    print(sess.run(j))

[0 1 2 3 4]


### random constants
- **tf.random_normal(shape, mean = 0.0, stddev = 1.0, dtype = tf.float32, seed = None, name = None)**
    - Outputs random values from a normal distribution.
- **tf.truncated_normal(shape, mean = 0.0, stddev = 1.0, dtype = tf.float32, seed = None, name = None)**
- **tf.random_uniform(shape, minval = 0, maxval = None, dtype =tf.float32, seed = None, name = None)**
- **tf.random_shuffle(value, seed = None, name= None)**
    - randomly shuffle a tensor along its first dimension.
- **tf.random_crop(value,size, seed = None, name = None)**
    - randomly crops a tensor to a given size
- **tf.multinomial(logits, num_samples, seed = None, name = None)**
    - it draws samples from a multinomial distribution
- **tf.random_gamma(shape,alpha, beta, dtype = tf.float32, seed = None, name = None) **

In [80]:
# normal distribution:
normal = tf.random_normal([2,3], mean = 20, stddev = 2)

# truncated normal distribution
tnormal = tf.truncated_normal([2,3], 20 ,2)
with tf.Session() as sess:
    print("Normal Distribution\n",sess.run(normal))
    print("Truncated Normal\n",sess.run(tnormal))


Normal Distribution
 [[ 22.91229057  21.07133293  18.27061844]
 [ 20.05288506  17.74287415  19.72896194]]
Truncated Normal
 [[ 20.18136215  20.25928307  18.27256203]
 [ 18.71704102  17.43005371  21.04504013]]


In [81]:
# random shuffle
abc = tf.constant([2,3,4,5,6])
shu = tf.random_shuffle(abc)
with tf.Session() as sess:
    print("No shuffle:", sess.run(abc))
    print("With shuffle:",sess.run(shu))
cde = tf.constant([[2,3],[4,5],[7,9]])
cdeshu = tf.random_shuffle(cde)
with tf.Session() as sess:
    print("No shuffle: \n", sess.run(cde))
    print("With shuffle:\n", sess.run(cdeshu))

No shuffle: [2 3 4 5 6]
With shuffle: [4 5 6 2 3]
No shuffle: 
 [[2 3]
 [4 5]
 [7 9]]
With shuffle:
 [[2 3]
 [7 9]
 [4 5]]


In [82]:
# random crop: randomly crops a tensor to a given size.
# If a dimension should not be cropped, for example an image with RGB values, then you could do
# size = [crop_height, crop_width, 3]
a = tf.random_normal([7,3])
# crop this to a 3 by 2 matrix
b = tf.random_crop(a,[3,2] ,name = "cropped")
print(b)

Tensor("cropped_1:0", shape=(3, 2), dtype=float32)


In [83]:
# multinomial: 
# samples has shape [1, 5], where each value is either 0 or 1 with equal
# probability.
samples = tf.multinomial(tf.log([[10., 10.]]), 5)
with tf.Session() as sess:
    print(sess.run(samples))

[[1 1 1 1 0]]


## 3. [Math Operations](https://www.tensorflow.org/api_guides/python/math_ops):
- prety stndard, similar to Numpy

In [104]:
a = tf.constant([[3,6,4],[2,4,1]])
b = tf.constant([[2,2,3],[1,2,4]])
added = tf.add(a,b)
addN = tf.add_n([a,b,b]) # notice the brackets? 
mul = tf.multiply(a,b) # multiply is element wise
matmultiply = tf.matmul(a,tf.transpose(b))
divide = tf.div(a,b)
modulus = tf.mod(a,b)

with tf.Session() as sess:
    print("a: \n", sess.run(a), "\n b \n",sess.run(b))
    print("Added: \n",sess.run(added))
    print("Add n #s \n",sess.run(addN))
    print("Element-wise mul\n",sess.run(mul))
    print("Matrix mul \n",sess.run(matmultiply))
    print("Matrix div \n" ,sess.run(divide), "\n matrix modulus\n",sess.run(modulus))

a: 
 [[3 6 4]
 [2 4 1]] 
 b 
 [[2 2 3]
 [1 2 4]]
Added: 
 [[5 8 7]
 [3 6 5]]
Add n #s 
 [[ 7 10 10]
 [ 4  8  9]]
Element-wise mul
 [[ 6 12 12]
 [ 2  8  4]]
Matrix mul 
 [[30 31]
 [15 14]]
Matrix div 
 [[1 3 1]
 [2 2 0]] 
 matrix modulus
 [[1 0 1]
 [0 0 1]]
